openapi: 3.0.0
info:
  title: Holdings-Items
  description: Interface for adding/removing/updating holdings-items
  contact:
    url: mailto:dbc@dbc.dk
  version: "1.0"
servers:
- url: http:/
paths:
  /api/v1/holdings/{agencyId}/{bibliographicRecordId}:
    get:
      summary: Retrieve all holding for this bibliographic record
      description: Retrieve a payload of all issues/items for this bibliographic record
        id.
      parameters:
      - $ref: '#/components/parameters/agencyId'
      - $ref: '#/components/parameters/bibliographicRecordId'
      - $ref: '#/components/parameters/trackingId'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompleteExport'
          description: All the holdings for this bibliographic record
        "400":
          $ref: '#/components/responses/bad_request'
        "404":
          $ref: '#/components/responses/not_found'
    put:
      summary: Update all holdings for bibliographic record (complete)
      description: Receives a payload of all issues/items for this bibliographic record
        id. All issues/items that are not references are removed. Items are moved
        (stolen) from other bibliographic records. Bibliographic record id is translated
        according to supersedes rules.
      parameters:
      - $ref: '#/components/parameters/agencyId'
      - $ref: '#/components/parameters/bibliographicRecordId'
      - $ref: '#/components/parameters/trackingId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompleteWithIssues'
      responses:
        "200":
          $ref: '#/components/responses/success'
        "400":
          $ref: '#/components/responses/bad_request'
    delete:
      summary: Remove all holdings for bibliographic record
      description: "Removes all issues/items for a bibliographic record, This will\
        \ also lose firstAccessionDate, for any items not resurrected."
      parameters:
      - $ref: '#/components/parameters/agencyId'
      - $ref: '#/components/parameters/bibliographicRecordId'
      - $ref: '#/components/parameters/trackingId'
      responses:
        "200":
          $ref: '#/components/responses/success'
        "400":
          $ref: '#/components/responses/bad_request'
  /api/v1/holdings/{agencyId}/{bibliographicRecordId}/{itemId}:
    put:
      summary: Update a single holding for a bibliographic record
      description: "Receives a payload of an item with related issue for this bibliographic\
        \ record id. Items are moved (stolen) from other bibliographic records. Bibliographic\
        \ record id is translated according to supersedes rules. If the bibliographic\
        \ record does not exist, a bad request response is given."
      parameters:
      - $ref: '#/components/parameters/agencyId'
      - $ref: '#/components/parameters/bibliographicRecordId'
      - $ref: '#/components/parameters/itemId'
      - $ref: '#/components/parameters/trackingId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemWithIssue'
      responses:
        "200":
          $ref: '#/components/responses/success'
        "400":
          $ref: '#/components/responses/bad_request'
  /api/v1/lookup/agencies-with-holdings/{bibliographicRecordId}:
    get:
      summary: Endpoint for asking for agencies that holdings for a bibliographic-record-id
      description: "Endpoing to query if this bibliographic-record-id can be removed.\
        \ The response contains all agencies, that have holdings that are not of type\
        \ (Discarded). An empty list is it is ok to remove this id."
      parameters:
      - $ref: '#/components/parameters/bibliographicRecordId'
      - $ref: '#/components/parameters/trackingId'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgenciesWithHoldings'
          description: The agencies that has holding on this bibliographic-record-id
        "400":
          $ref: '#/components/responses/bad_request'
        "404":
          $ref: '#/components/responses/not_found'
  /api/v1/lookup/holdings-by-bibliographic-record-ids/{agencyId}:
    get:
      summary: Endpoint for asking for holdings for bibliographical identifiers for
        an agencies
      description: The response is a list of all holdings for all records that match
        the agency identifier and the bibliographical identifiers with optional branchId
        parameter.
      parameters:
      - $ref: '#/components/parameters/agencyId'
      - name: branchId
        in: query
        description: Optional Identifying number of the branch
        required: false
        allowEmptyValue: false
        schema:
          maximum: 999999
          minimum: 100000
          type: number
        example: 710104
      - name: bibliographicRecordId
        in: query
        description: bibliographic record id (faust number)
        required: true
        allowEmptyValue: false
        schema:
          type: array
          items:
            type: string
        example: "51068432"
      - $ref: '#/components/parameters/trackingId'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompleteExport'
          description: All the holdings for this bibliographic record
        "400":
          $ref: '#/components/responses/bad_request'
        "404":
          $ref: '#/components/responses/not_found'
  /api/v1/lookup/holdings-by-item-id/{agencyId}/{itemId}:
    get:
      summary: Endpoint for asking for holdings for an agency and item
      description: The response is a list of all holdings for all records thar match
        the agency and item identifier
      parameters:
      - $ref: '#/components/parameters/agencyId'
      - $ref: '#/components/parameters/itemId'
      - $ref: '#/components/parameters/trackingId'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompleteExport'
          description: All the holdings for this agency and item id
        "400":
          $ref: '#/components/responses/bad_request'
        "404":
          $ref: '#/components/responses/not_found'
  /api/v1/lookup/holdings-by-status/{agencyId}:
    get:
      summary: Endpoint for asking for holdings for bibliographical identifiers for
        an agencies
      description: The response is a list of all holdings for all records that match
        the agency identifier and the bibliographical identifiers with optional branchId
        parameter.
      parameters:
      - $ref: '#/components/parameters/agencyId'
      - $ref: '#/components/parameters/trackingId'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusByAgency'
          description: All the holdings for this bibliographic record
        "400":
          $ref: '#/components/responses/bad_request'
        "404":
          $ref: '#/components/responses/not_found'
  /api/v1/supersedes/{bibliographicRecordId}:
    get:
      summary: Endpoint for supersedes updated/inserted
      description: Receives a payload of bibliographic record ids that are superseded
        by the one in the path. Then rearranges the database to reflect this.
      parameters:
      - $ref: '#/components/parameters/bibliographicRecordId'
      - $ref: '#/components/parameters/trackingId'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Supersedes'
          description: The records that are superseded
        "400":
          $ref: '#/components/responses/bad_request'
        "404":
          $ref: '#/components/responses/not_found'
    put:
      summary: Endpoint for supersedes updated/inserted
      description: Receives a payload of bibliographic record ids that are superseded
        by the one in the path. Then rearranges the database to reflect this.
      parameters:
      - $ref: '#/components/parameters/bibliographicRecordId'
      - $ref: '#/components/parameters/trackingId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Supersedes'
      responses:
        "200":
          $ref: '#/components/responses/success'
        "400":
          $ref: '#/components/responses/bad_request'
    delete:
      summary: Endpoint for supersedes removing
      description: Not implemented - superseded is a one way action
      parameters:
      - $ref: '#/components/parameters/bibliographicRecordId'
      - $ref: '#/components/parameters/trackingId'
      responses:
        "200":
          $ref: '#/components/responses/success'
        "400":
          $ref: '#/components/responses/bad_request'
endpoints:
  /:
  - "/api/v1/holdings/{agencyId}/{bibliographicRecordId}"
  - "/api/v1/holdings/{agencyId}/{bibliographicRecordId}/{itemId}"
  - "/api/v1/lookup/agencies-with-holdings/{bibliographicRecordId}"
  - "/api/v1/lookup/holdings-by-bibliographic-record-ids/{agencyId}"
  - "/api/v1/lookup/holdings-by-item-id/{agencyId}/{itemId}"
  - "/api/v1/lookup/holdings-by-status/{agencyId}"
  - "/api/v1/supersedes/{bibliographicRecordId}"
components:
  schemas:
    AgenciesWithHoldings:
      type: object
      properties:
        agencies:
          type: array
          description: Agencies in no particular order
          nullable: false
          example:
          - 710100
          - 756700
          items:
            maximum: 999999
            minimum: 100000
            type: number
            description: Identifying the agencyId that has holdings
            nullable: false
        trackingId:
          example: uuid
          $ref: '#/components/schemas/trackingId'
    CompleteExport:
      required:
      - agencyId
      - bibliographicRecordId
      type: object
      properties:
        agencyId:
          maximum: 999999
          minimum: 100000
          type: number
          description: Identifying the agencyId that owns this
          nullable: false
          example: 756700
        bibliographicRecordId:
          maximum: 9999999999
          minimum: 0
          type: number
          description: Identifying the agencyId that owns this
          nullable: false
          example: 25912233
      allOf:
      - $ref: '#/components/schemas/CompleteWithIssues'
    CompleteWithIssues:
      required:
      - version
      - firstAccessionDate
      - note
      type: object
      properties:
        version:
          type: string
          description: when this structure was exported in ISO-8601 format with timezone
            Z
          nullable: false
          example: 2024-01-04T12:45:01.333Z
        firstAccessionDate:
          type: string
          description: When the first item for this material was acquired ISO-8601
            format
          nullable: true
          example: 2024-01-04
        note:
          type: string
        issues:
          description: Issue-id to
          additionalProperties:
            $ref: '#/components/schemas/IssueWithItems'
        online:
          type: boolean
          description: Ia an online access for this bibliographic item is available
          nullable: true
      description: Request for a complete update of a bibliographic item
    Issue:
      required:
      - issueText
      - readyForLoan
      type: object
      properties:
        issueText:
          type: string
          description: The text describing the issue - for magazines et. al. - use
            an empty string when no issues are present
          nullable: false
        expectedDelivery:
          type: string
          description: When an item is expeced to be available for loan in ISO-8601
            format
          nullable: true
          example: 2024-01-04
        readyForLoan:
          minimum: 0
          type: number
          description: How many items are ready to be lent out. If 0 expectedDelivery
            is required to be set
          nullable: true
          example: 0
      description: Grouping of an issue (specifically for magazines et. al.)
    IssueWithItems:
      required:
      - items
      type: object
      properties:
        items:
          description: Item id to
          additionalProperties:
            $ref: '#/components/schemas/Item'
      allOf:
      - $ref: '#/components/schemas/Issue'
    Item:
      required:
      - branch
      - branchId
      - department
      - location
      - subLocation
      - circulationRule
      - accessionDate
      - status
      type: object
      properties:
        branch:
          type: string
          description: Human readable text describing the branch
          nullable: false
          example: Hovedebiblioteket
        branchId:
          maximum: 999999
          minimum: 100000
          type: number
          description: Identifying number of the branch
          nullable: false
          example: 710104
        department:
          type: string
          description: Human readable text describing the department within the branch
          nullable: false
          example: Voksen
        location:
          type: string
          description: Human readable text describing the location within the department
          nullable: false
          example: Lydbøger
        subLocation:
          type: string
          description: Human readable text describing the sub-location within the
            location
          nullable: false
          example: CD
        section:
          type: string
          description: Section within the location
          nullable: true
        floatGroup:
          type: string
          description: Float group for the item
          nullable: true
        circulationRule:
          type: string
          description: Human readable text describing the rules for lending
          nullable: false
          example: Normal udlån
        accessionDate:
          type: string
          description: When an item was acquired in ISO-8601 format
          nullable: false
          example: 2024-01-04
        loanRestriction:
          type: string
          description: Rule for lending according to DanMarc 096r
          nullable: true
          example: f
          enum:
          - ""
          - a
          - b
          - c
          - d
          - e
          - f
          - g
        status:
          type: string
          description: The status of the item
          enum:
          - Discarded
          - Lost
          - NotForLoan
          - OnLoan
          - OnOrder
          - OnShelf
        lastLoanDate:
          type: string
          description: When this item was lent
          nullable: true
          example: 2024-01-04
        ownerAgencyId:
          maximum: 999999
          minimum: 100000
          type: number
          description: "Identifying the agencyId that owns this, if it is temporarily\
            \ part of the library (ILL loan)"
          nullable: true
          example: 756700
    ItemWithIssue:
      required:
      - version
      - issue
      type: object
      properties:
        version:
          type: string
          description: when this structure was exported in ISO-8601 format with timezone
            Z
          nullable: false
          example: 2024-01-04T12:45:01.333Z
        issue:
          allOf:
          - $ref: '#/components/schemas/Issue'
          - required:
            - issueId
            type: object
            properties:
              issueId:
                type: string
                description: Issue-id
                nullable: false
      description: "For updating an item, with values for issue (for multiple items)"
      allOf:
      - $ref: '#/components/schemas/Item'
    StatusByAgency:
      type: object
      properties:
        agencyId:
          type: number
        trackingId:
          type: string
        statusCount:
          type: array
          description: Number of records that have the same status
          items:
            required:
            - status
            - count
            type: object
            properties:
              status:
                type: string
                description: Status
                nullable: false
                example: OnLine
              count:
                type: number
                description: Number of holdings with that status
                nullable: false
                example: 1
      description: Number of records that have the same status
    Supersedes:
      type: object
      properties:
        supersedes:
          type: array
          description: ids that are superseded
          items:
            type: string
            description: bibliographicRecordId (faust number)
            nullable: false
      description: Payload of records that supersedes other records - according to
        DanMarc 002a
      example:
        supersedes:
        - "51068440"
        - "51068459"
        - "51068467"
    status:
      type: object
      properties:
        ok:
          type: boolean
          description: If the call was a success
          nullable: false
          example: false
        message:
          type: string
          description: Human readable message about reason for the ok value
          nullable: false
          example: Database is gone
        trackingId:
          example: uuid
          $ref: '#/components/schemas/trackingId'
    trackingId:
      type: string
      description: "Useful for tracking a request in log files, will be generated\
        \ automatically is missing"
      nullable: true
      example: uuid
  responses:
    bad_request:
      description: An error occurred while mapping the incoming content / parameters.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/status'
    not_found:
      description: The resource was not found.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/status'
    success:
      description: The data was successfully (see `ok` in json) updated/inserted
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/status'
  parameters:
    agencyId:
      name: agencyId
      in: path
      description: library number
      required: true
      allowEmptyValue: false
      schema:
        maximum: 999999
        minimum: 100000
        type: number
      example: 710100
    bibliographicRecordId:
      name: bibliographicRecordId
      in: path
      description: bibliographic record id (faust number)
      required: true
      allowEmptyValue: false
      schema:
        type: string
      example: "51068432"
    branchId:
      name: branchId
      in: path
      description: Identifying number of the branch
      required: true
      allowEmptyValue: false
      schema:
        maximum: 999999
        minimum: 100000
        type: number
      example: 710104
    itemId:
      name: itemId
      in: path
      description: Identigier foe a material - usually a barcode
      required: true
      allowEmptyValue: false
      schema:
        type: string
      example: "3630767686"
    trackingId:
      name: trackingId
      in: query
      description: "Useful for tracking a request in log files, will be generated\
        \ automatically"
      required: false
      allowEmptyValue: false
      schema:
        type: string
      example: uuid
