// default rootfields and denytypes
const defaultSettings = {
  allowRootFields: [
    "debug",
    "draft",
    "manifestation",
    "manifestations",
    "search",
    "work",
    "works",
    "search",
    "suggest",
    "complexSearch",
    "complexSuggest",
    "localSuggest",
    "recommend",
    "infomedia",
    "refWorks",
    "ris",
    "elba",
    "library",
    "relatedSubjects",
    "linkCheck",
    "series",
    "universe",
    "mood",
  ],
  denyTypes: ["CheckOrderPolicy", "Availability", "SEO"],
};

// smaug roles map in fbi-api
export default {
  bibdk: {
    allowRootFields: [
      ...defaultSettings.allowRootFields,
      "bibdk",
      "monitor",
      "complexFacets",
      "help",
      "branches",
      "session",
      "localizations",
      "localizationsWithHoldings",
      "ris",
      "inspiration",
      "orderStatus",
      "test",
      "user",
      "submitOrder",
      "submitMultipleOrders",
      "data_collect",
      "deleteOrder",
      "renewLoan",
      "submitSession",
      "deleteSession",
      "users",
    ],
    denyTypes: [],
  },
  "fbs:system": {
    allowRootFields: ["culr", "vip"],
    denyTypes: [],
  },
  ddbcms: {
    allowRootFields: [...defaultSettings.allowRootFields, "submitOrder"],
    denyTypes: [...defaultSettings.denyTypes, "WorkReview"],
  },
  default: defaultSettings,
};
